### ISSUE TITLE
Is there any plans to merge it with main repository?

### ISSUE THREAD

**Issue by skupr** [Slimmmo/dev#2]
Hi!

Didn't know how to contact you by other methods, so decided to write here.

I started to implement savegame import for main version. Then I've found this dev repository - and it seems that it's already here. But overall, this dev version seems to be more unstable; also, there is no development activity since April.
So the questions:
Do you plan to maintain this dev repository?
Is there any plans to merge dev repository code from/to main ACC repository?

**Comment by Slimmmo** [comment]
Hi,

The save game import in this repo is completely untested and incomplete so if you want to work on it to get it into a working state I'll happily implement it in the main version.

I have no plans on what to do with this dev repo so for the moment it's just sitting here.

Thanks.

**Comment by skupr** [comment]
Thank you!

P.S. I also like new navbar in this dev version.
